ini_row_start = 2
mid_row_start = 12
fin_row_start = 16

ini_variants = [
    ".[ㅏㅐㅑㅒㅓㅔㅕㅖㅣ]0",
    ".[ㅗㅛㅡ]0",
    ".[ㅜㅠ]0",
    ".[ㅘㅙㅚㅢ]0",
    ".[ㅝㅞㅟ]0",
    ".[ㅏㅐㅑㅒㅓㅔㅕㅖㅣ][^0]",
    ".[ㅗㅛㅡ][^0]",
    ".[ㅜㅠ][^0]",
    ".[ㅘㅙㅚㅢ][^0]",
    ".[ㅝㅞㅟ][^0]",
]

mid_variants = [
    "[ㄱㅋ].0",
    "[^ㄱㅋ].0",
    "[ㄱㅋ].[^0]",
    "[^ㄱㅋ].[^0]",
]

fin_variants = [
    ".[ㅏㅑㅘ].",
    ".[ㅓㅕㅚㅝㅟㅢㅣ].",
    ".[ㅐㅒㅔㅖㅙㅞ].",
    ".[ㅗㅛㅜㅠㅡ].",
]
